
/* MODULE io_tables. */
#include "io_tables.h"

#include "adConvCom1.h"
#include "flexTimerCom1.h"





#include "device_registers.h"

/*! @brief Array of pin configuration structures */
pin_settings_config_t g_pin_mux_InitConfigArr[NUM_OF_CONFIGURED_PINS] = {

//            - PORTA -             ,  - PORTA -                ,  - PORTA -                                            ,  - PORTA -                      ,  - PORTA -                                       ,  - PORTA -                        ,  - PORTA -                ,  - PORTA -                                  ,  - PORTA -                     ,  - PORTA -               ,  - PORTA -                    ,               - PORTA -                  
             // .base               , // pinPortIndex           , // pullConfig                                         , // passiveFilter                , // driveSelect                                   , // mux                            , // pinLock                , // intConfig                                , // clearIntFlag                , // gpioBase              , // direction                  ,              // pin name                 
{            .base = PORTA          , .pinPortIdx = 0           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_IN            , },           // DI_AI_OUT1               
{            .base = PORTA          , .pinPortIdx = 1           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_IN            , },           // DI_AI_OUT4               
{            .base = PORTA          , .pinPortIdx = 2           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_IN            , },           // DI_AI_OUT6               
{            .base = PORTA          , .pinPortIdx = 3           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_IN            , },           // DI_AI_OUT7               
{            .base = PORTA          , .pinPortIdx = 4           , .pullConfig = PORT_INTERNAL_PULL_UP_ENABLED           , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT7              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = 0            , .direction = PD_NONE          , },           // MC_JTAG_TMS              
{            .base = PORTA          , .pinPortIdx = 5           , .pullConfig = PORT_INTERNAL_PULL_UP_ENABLED           , .passiveFilter = true           , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT7              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = 0            , .direction = PD_NONE          , },           // MC_JTAG_TRST             
{            .base = PORTA          , .pinPortIdx = 6           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_IN            , },           // DI_AI_A_IN3              
{            .base = PORTA          , .pinPortIdx = 7           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_IN            , },           // DI_AI_A_IN2              
{            .base = PORTA          , .pinPortIdx = 8           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = 0            , .direction = PD_NONE          , },           // MC_SCI_RXD               
{            .base = PORTA          , .pinPortIdx = 9           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = 0            , .direction = PD_NONE          , },           // MC_SCI_TXD               
{            .base = PORTA          , .pinPortIdx = 10          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_HIGH_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT7              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = 0            , .direction = PD_NONE          , },           // MC_JTAG_TDO              
{            .base = PORTA          , .pinPortIdx = 11          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_OUT           , },           // CAN_EN1                  
{            .base = PORTA          , .pinPortIdx = 12          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT3              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = 0            , .direction = PD_NONE          , },           // MC_CAN_RXD2              
{            .base = PORTA          , .pinPortIdx = 13          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT3              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = 0            , .direction = PD_NONE          , },           // MC_CAN_TXD2              
{            .base = PORTA          , .pinPortIdx = 14          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_OUT           , },           // CAN_WAKE1                
{            .base = PORTA          , .pinPortIdx = 15          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_IN            , },           // DI_AI_OUT2               
{            .base = PORTA          , .pinPortIdx = 16          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_IN            , },           // DI_AI_OUT3               
{            .base = PORTA          , .pinPortIdx = 17          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_IN            , },           // DI_PGD                   
//            - PORTB -             ,  - PORTB -                ,  - PORTB -                                            ,  - PORTB -                      ,  - PORTB -                                       ,  - PORTB -                        ,  - PORTB -                ,  - PORTB -                                  ,  - PORTB -                     ,  - PORTB -               ,  - PORTB -                    ,               - PORTB -                  
             // .base               , // pinPortIndex           , // pullConfig                                         , // passiveFilter                , // driveSelect                                   , // mux                            , // pinLock                , // intConfig                                , // clearIntFlag                , // gpioBase              , // direction                  ,              // pin name                 
{            .base = PORTB          , .pinPortIdx = 0           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_IN            , },           // DI_AI_A_IN1              
{            .base = PORTB          , .pinPortIdx = 1           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_IN            , },           // DI_AI_A_IN0              
{            .base = PORTB          , .pinPortIdx = 2           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_IN            , },           // DI_AI_INA_OUT4           
{            .base = PORTB          , .pinPortIdx = 3           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_IN            , },           // DI_AI_INA_OUT7           
{            .base = PORTB          , .pinPortIdx = 4           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // DO_HSD1_OUT1             
{            .base = PORTB          , .pinPortIdx = 5           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // DO_HSD1_OUT3             
{            .base = PORTB          , .pinPortIdx = 6           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = 0            , .direction = PD_NONE          , },           // XTAL                     
{            .base = PORTB          , .pinPortIdx = 7           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = 0            , .direction = PD_NONE          , },           // EXTAL                    
{            .base = PORTB          , .pinPortIdx = 8           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // DO_RS2                   
{            .base = PORTB          , .pinPortIdx = 9           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_IN            , },           // MC_FREQ_A_IN4            
{            .base = PORTB          , .pinPortIdx = 10          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_IN            , },           // MC_FREQ_A_IN5            
{            .base = PORTB          , .pinPortIdx = 11          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // DO_RS4                   
{            .base = PORTB          , .pinPortIdx = 12          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_IN            , },           // DI_AI_SNS4               
{            .base = PORTB          , .pinPortIdx = 13          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_IN            , },           // DI_AI_SNS1               
{            .base = PORTB          , .pinPortIdx = 14          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_IN            , },           // DI_AI_SNS2               
{            .base = PORTB          , .pinPortIdx = 15          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_IN            , },           // DI_AI_A_IN5              
{            .base = PORTB          , .pinPortIdx = 16          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_IN            , },           // DI_AI_A_IN4              
{            .base = PORTB          , .pinPortIdx = 17          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // DO_RS5                   
//            - PORTC -             ,  - PORTC -                ,  - PORTC -                                            ,  - PORTC -                      ,  - PORTC -                                       ,  - PORTC -                        ,  - PORTC -                ,  - PORTC -                                  ,  - PORTC -                     ,  - PORTC -               ,  - PORTC -                    ,               - PORTC -                  
             // .base               , // pinPortIndex           , // pullConfig                                         , // passiveFilter                , // driveSelect                                   , // mux                            , // pinLock                , // intConfig                                , // clearIntFlag                , // gpioBase              , // direction                  ,              // pin name                 
{            .base = PORTC          , .pinPortIdx = 0           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_IN            , },           // DI_AI_INA_OUT3           
{            .base = PORTC          , .pinPortIdx = 1           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_IN            , },           // DI_AI_INA_OUT2           
{            .base = PORTC          , .pinPortIdx = 2           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_IN            , },           // DI_AI_KL30_1             
{            .base = PORTC          , .pinPortIdx = 3           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_IN            , },           // DI_AI_KL30_2             
{            .base = PORTC          , .pinPortIdx = 4           , .pullConfig = PORT_INTERNAL_PULL_DOW_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT7              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = 0            , .direction = PD_NONE          , },           // MC_JTAG_TCLK             
{            .base = PORTC          , .pinPortIdx = 5           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT7              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = 0            , .direction = PD_NONE          , },           // MC_JTAG_TDI              
{            .base = PORTC          , .pinPortIdx = 6           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_IN            , },           // DI_AI_VARIANTE           
{            .base = PORTC          , .pinPortIdx = 7           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_IN            , },           // DI_AI_ID                 
{            .base = PORTC          , .pinPortIdx = 8           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_OUT           , },           // DO_RS3                   
{            .base = PORTC          , .pinPortIdx = 9           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_OUT           , },           // DO_RS0                   
{            .base = PORTC          , .pinPortIdx = 10          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_IN            , },           // MC_FREQ_A_IN0            
{            .base = PORTC          , .pinPortIdx = 11          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_IN            , },           // MC_FREQ_A_IN1            
{            .base = PORTC          , .pinPortIdx = 12          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_IN            , },           // MC_FREQ_A_IN2            
{            .base = PORTC          , .pinPortIdx = 13          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_IN            , },           // MC_FREQ_A_IN3            
{            .base = PORTC          , .pinPortIdx = 14          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_IN            , },           // DI_AI_INA_OUT5           
{            .base = PORTC          , .pinPortIdx = 15          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_IN            , },           // DI_AI_INA_OUT6           
{            .base = PORTC          , .pinPortIdx = 16          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_IN            , },           // DI_AI_INA_OUT0           
{            .base = PORTC          , .pinPortIdx = 17          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_IN            , },           // DI_AI_INA_OUT1           
//            - PORTD -             ,  - PORTD -                ,  - PORTD -                                            ,  - PORTD -                      ,  - PORTD -                                       ,  - PORTD -                        ,  - PORTD -                ,  - PORTD -                                  ,  - PORTD -                     ,  - PORTD -               ,  - PORTD -                    ,               - PORTD -                  
             // .base               , // pinPortIndex           , // pullConfig                                         , // passiveFilter                , // driveSelect                                   , // mux                            , // pinLock                , // intConfig                                , // clearIntFlag                , // gpioBase              , // direction                  ,              // pin name                 
{            .base = PORTD          , .pinPortIdx = 0           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_SHIFT_SH_CP           
{            .base = PORTD          , .pinPortIdx = 1           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_SHIFT_ST_CP           
{            .base = PORTD          , .pinPortIdx = 2           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_IN            , },           // DI_AI_OUT5               
{            .base = PORTD          , .pinPortIdx = 3           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_IN            , },           // DI_AI_VREF               
{            .base = PORTD          , .pinPortIdx = 4           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_IN            , },           // DI_AI_SNS3               
{            .base = PORTD          , .pinPortIdx = 5           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_HSD2_OUT4             
{            .base = PORTD          , .pinPortIdx = 6           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DOX_SHIFT_IN_DS          
{            .base = PORTD          , .pinPortIdx = 7           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_IN            , },           // DI_INTERFACE2_A          
{            .base = PORTD          , .pinPortIdx = 8           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_IN            , },           // DI_INTERFACE2_B          
{            .base = PORTD          , .pinPortIdx = 9           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT6              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_HSD2_OUT6             
{            .base = PORTD          , .pinPortIdx = 10          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_VREF_EN               
{            .base = PORTD          , .pinPortIdx = 11          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_CS_HSD2               
{            .base = PORTD          , .pinPortIdx = 12          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_HSD2_OUT5             
{            .base = PORTD          , .pinPortIdx = 13          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_IN            , },           // DI_KL15                  
{            .base = PORTD          , .pinPortIdx = 14          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_HSD1_OUT0             
{            .base = PORTD          , .pinPortIdx = 15          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_POWER                 
{            .base = PORTD          , .pinPortIdx = 16          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_HSD2_OUT7             
{            .base = PORTD          , .pinPortIdx = 17          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_CS_HSD1               
//            - PORTE -             ,  - PORTE -                ,  - PORTE -                                            ,  - PORTE -                      ,  - PORTE -                                       ,  - PORTE -                        ,  - PORTE -                ,  - PORTE -                                  ,  - PORTE -                     ,  - PORTE -               ,  - PORTE -                    ,               - PORTE -                  
             // .base               , // pinPortIndex           , // pullConfig                                         , // passiveFilter                , // driveSelect                                   , // mux                            , // pinLock                , // intConfig                                , // clearIntFlag                , // gpioBase              , // direction                  ,              // pin name                 
{            .base = PORTE          , .pinPortIdx = 0           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_IN            , },           // CAN_ERR1                 
{            .base = PORTE          , .pinPortIdx = 1           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // CAN_STB1                 
{            .base = PORTE          , .pinPortIdx = 2           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = 0            , .direction = PD_NONE          , },           // Pin74                    
{            .base = PORTE          , .pinPortIdx = 3           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // CAN_STB2                 
{            .base = PORTE          , .pinPortIdx = 4           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT5              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = 0            , .direction = PD_NONE          , },           // MC_CAN_RXD1              
{            .base = PORTE          , .pinPortIdx = 5           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT5              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = 0            , .direction = PD_NONE          , },           // MC_CAN_TXD1              
{            .base = PORTE          , .pinPortIdx = 6           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_IN            , },           // DI_AI_OUT0               
{            .base = PORTE          , .pinPortIdx = 7           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // DO_RS1                   
{            .base = PORTE          , .pinPortIdx = 8           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // DO_HSD1_OUT2             
{            .base = PORTE          , .pinPortIdx = 9           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // LIN_EN                   
{            .base = PORTE          , .pinPortIdx = 10          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = 0            , .direction = PD_NONE          , },           // Pin82                    
{            .base = PORTE          , .pinPortIdx = 11          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_NONE          , },           // WD                       
{            .base = PORTE          , .pinPortIdx = 12          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // CAN_EN2                  
{            .base = PORTE          , .pinPortIdx = 13          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_IN            , },           // CAN_ERR2                 
{            .base = PORTE          , .pinPortIdx = 14          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // CAN_WAKE2                
{            .base = PORTE          , .pinPortIdx = 15          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // DO_SHIFT_OE              
{            .base = PORTE          , .pinPortIdx = 16          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH           , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // DO_SHIFT_MR              
  
};

/* struct_io_pin_linker_t array contains link beetween pin_name/virtual_pin_name and asociated adc_pin_name/pwm_pin_name */
const struct_io_pin_linker_t io_pin_linker[VIRTUAL_PIN_MAX]=
{
//            - PORTA -                           ,  - PORTA -                                           - PORTA -                  
{            .adc_pin_name = AI_OUT1              , .pwm_pin_name = PWM_MAX                 },          // DI_AI_OUT1               
{            .adc_pin_name = AI_OUT4              , .pwm_pin_name = PWM_MAX                 },          // DI_AI_OUT4               
{            .adc_pin_name = AI_OUT6              , .pwm_pin_name = PWM_MAX                 },          // DI_AI_OUT6               
{            .adc_pin_name = AI_OUT7              , .pwm_pin_name = PWM_MAX                 },          // DI_AI_OUT7               
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // MC_JTAG_TMS              
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // MC_JTAG_TRST             
{            .adc_pin_name = AI_A_IN3             , .pwm_pin_name = PWM_MAX                 },          // DI_AI_A_IN3              
{            .adc_pin_name = AI_A_IN2             , .pwm_pin_name = PWM_MAX                 },          // DI_AI_A_IN2              
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // MC_SCI_RXD               
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // MC_SCI_TXD               
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // MC_JTAG_TDO              
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // CAN_EN1                  
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // MC_CAN_RXD2              
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // MC_CAN_TXD2              
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // CAN_WAKE1                
{            .adc_pin_name = AI_OUT2              , .pwm_pin_name = PWM_MAX                 },          // DI_AI_OUT2               
{            .adc_pin_name = AI_OUT3              , .pwm_pin_name = PWM_MAX                 },          // DI_AI_OUT3               
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DI_PGD                   
//            - PORTB -                           ,  - PORTB -                                           - PORTB -                  
{            .adc_pin_name = AI_A_IN1             , .pwm_pin_name = PWM_MAX                 },          // DI_AI_A_IN1              
{            .adc_pin_name = AI_A_IN0             , .pwm_pin_name = PWM_MAX                 },          // DI_AI_A_IN0              
{            .adc_pin_name = AI_INA_OUT4          , .pwm_pin_name = PWM_MAX                 },          // DI_AI_INA_OUT4           
{            .adc_pin_name = AI_INA_OUT7          , .pwm_pin_name = PWM_MAX                 },          // DI_AI_INA_OUT7           
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_HSD1_OUT1           },          // DO_HSD1_OUT1             
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_HSD1_OUT3           },          // DO_HSD1_OUT3             
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // XTAL                     
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // EXTAL                    
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DO_RS2                   
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = FREQ_A_IN4              },          // MC_FREQ_A_IN4            
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = FREQ_A_IN5              },          // MC_FREQ_A_IN5            
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DO_RS4                   
{            .adc_pin_name = AI_SNS4              , .pwm_pin_name = PWM_MAX                 },          // DI_AI_SNS4               
{            .adc_pin_name = AI_SNS1              , .pwm_pin_name = PWM_MAX                 },          // DI_AI_SNS1               
{            .adc_pin_name = AI_SNS2              , .pwm_pin_name = PWM_MAX                 },          // DI_AI_SNS2               
{            .adc_pin_name = AI_A_IN5             , .pwm_pin_name = PWM_MAX                 },          // DI_AI_A_IN5              
{            .adc_pin_name = AI_A_IN4             , .pwm_pin_name = PWM_MAX                 },          // DI_AI_A_IN4              
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DO_RS5                   
//            - PORTC -                           ,  - PORTC -                                           - PORTC -                  
{            .adc_pin_name = AI_INA_OUT3          , .pwm_pin_name = PWM_MAX                 },          // DI_AI_INA_OUT3           
{            .adc_pin_name = AI_INA_OUT2          , .pwm_pin_name = PWM_MAX                 },          // DI_AI_INA_OUT2           
{            .adc_pin_name = AI_KL30_1            , .pwm_pin_name = PWM_MAX                 },          // DI_AI_KL30_1             
{            .adc_pin_name = AI_KL30_2            , .pwm_pin_name = PWM_MAX                 },          // DI_AI_KL30_2             
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // MC_JTAG_TCLK             
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // MC_JTAG_TDI              
{            .adc_pin_name = AI_VARIANTE          , .pwm_pin_name = PWM_MAX                 },          // DI_AI_VARIANTE           
{            .adc_pin_name = AI_ID                , .pwm_pin_name = PWM_MAX                 },          // DI_AI_ID                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DO_RS3                   
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DO_RS0                   
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = FREQ_A_IN0              },          // MC_FREQ_A_IN0            
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = FREQ_A_IN1              },          // MC_FREQ_A_IN1            
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = FREQ_A_IN2              },          // MC_FREQ_A_IN2            
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = FREQ_A_IN3              },          // MC_FREQ_A_IN3            
{            .adc_pin_name = AI_INA_OUT5          , .pwm_pin_name = PWM_MAX                 },          // DI_AI_INA_OUT5           
{            .adc_pin_name = AI_INA_OUT6          , .pwm_pin_name = PWM_MAX                 },          // DI_AI_INA_OUT6           
{            .adc_pin_name = AI_INA_OUT0          , .pwm_pin_name = PWM_MAX                 },          // DI_AI_INA_OUT0           
{            .adc_pin_name = AI_INA_OUT1          , .pwm_pin_name = PWM_MAX                 },          // DI_AI_INA_OUT1           
//            - PORTD -                           ,  - PORTD -                                           - PORTD -                  
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DO_SHIFT_SH_CP           
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DO_SHIFT_ST_CP           
{            .adc_pin_name = AI_OUT5              , .pwm_pin_name = PWM_MAX                 },          // DI_AI_OUT5               
{            .adc_pin_name = AI_VREF              , .pwm_pin_name = PWM_MAX                 },          // DI_AI_VREF               
{            .adc_pin_name = AI_SNS3              , .pwm_pin_name = PWM_MAX                 },          // DI_AI_SNS3               
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_HSD2_OUT4           },          // DO_HSD2_OUT4             
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DOX_SHIFT_IN_DS          
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DI_INTERFACE2_A          
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DI_INTERFACE2_B          
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_HSD2_OUT6           },          // DO_HSD2_OUT6             
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DO_VREF_EN               
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DO_CS_HSD2               
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_HSD2_OUT5           },          // DO_HSD2_OUT5             
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DI_KL15                  
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_HSD1_OUT0           },          // DO_HSD1_OUT0             
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DO_POWER                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_HSD2_OUT7           },          // DO_HSD2_OUT7             
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DO_CS_HSD1               
//            - PORTE -                           ,  - PORTE -                                           - PORTE -                  
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // CAN_ERR1                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // CAN_STB1                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // Pin74                    
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // CAN_STB2                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // MC_CAN_RXD1              
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // MC_CAN_TXD1              
{            .adc_pin_name = AI_OUT0              , .pwm_pin_name = PWM_MAX                 },          // DI_AI_OUT0               
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DO_RS1                   
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_HSD1_OUT2           },          // DO_HSD1_OUT2             
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // LIN_EN                   
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // Pin82                    
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // WD                       
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // CAN_EN2                  
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // CAN_ERR2                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // CAN_WAKE2                
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DO_SHIFT_OE              
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DO_SHIFT_MR              
//            - VIRTUAL PINS -                    ,  - VIRTUAL PINS -                                    - VIRTUAL PINS -           
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DCDC_8V5                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // DCDC_10V                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // PD_A_IN5                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // PD_A_IN4                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // PD_A_IN3                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // PD_A_IN2                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // PD_A_IN1                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // PD_A_IN0                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // PU_A_IN5                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // PU_A_IN4                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // PU_A_IN3                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // PU_A_IN2                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // PU_A_IN1                 
{            .adc_pin_name = ADC_MAX              , .pwm_pin_name = PWM_MAX                 },          // PU_A_IN0                 
  
};

/* Virtual Pins configuration structure */
struct_VIRTUAL_PINS_CFG virtual_pin[VIRTUAL_PIN_MAX - PIN_MAX] = {
{ .name = DCDC_8V5          , .current_val = 0           },
{ .name = DCDC_10V          , .current_val = 0           },
{ .name = PD_A_IN5          , .current_val = 0           },
{ .name = PD_A_IN4          , .current_val = 0           },
{ .name = PD_A_IN3          , .current_val = 0           },
{ .name = PD_A_IN2          , .current_val = 0           },
{ .name = PD_A_IN1          , .current_val = 0           },
{ .name = PD_A_IN0          , .current_val = 0           },
{ .name = PU_A_IN5          , .current_val = 0           },
{ .name = PU_A_IN4          , .current_val = 0           },
{ .name = PU_A_IN3          , .current_val = 0           },
{ .name = PU_A_IN2          , .current_val = 0           },
{ .name = PU_A_IN1          , .current_val = 0           },
{ .name = PU_A_IN0          , .current_val = 0           },
  
};


/* ADC configuration structure */
const struct_adc_config_t adc_config_tbl[ADC_MAX + 1] = {
            // adc_instance                       , // adc_channel             , // adc_vref high            , // resolution               , // multiplex                , // multiplex group             , // cal_index              , // calibration type                                                                 
{           .adc_instance = INST_ADCONV1          , .adc_channel = 5           , .adc_vrefh = 16920          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_A_IN0                  
{           .adc_instance = INST_ADCONV1          , .adc_channel = 4           , .adc_vrefh = 16920          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_A_IN1                  
{           .adc_instance = INST_ADCONV1          , .adc_channel = 3           , .adc_vrefh = 16920          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_A_IN2                  
{           .adc_instance = INST_ADCONV1          , .adc_channel = 2           , .adc_vrefh = 16920          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_A_IN3                  
{           .adc_instance = INST_ADCONV2          , .adc_channel = 15          , .adc_vrefh = 16920          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_A_IN4                  
{           .adc_instance = INST_ADCONV2          , .adc_channel = 14          , .adc_vrefh = 16920          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_A_IN5                  
{           .adc_instance = INST_ADCONV2          , .adc_channel = 5           , .adc_vrefh = 16920          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_ID                     
{           .adc_instance = INST_ADCONV1          , .adc_channel = 14          , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_SOURCE_SINK_3P           },          // AI_INA_OUT0               
{           .adc_instance = INST_ADCONV1          , .adc_channel = 15          , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 24           , .cal_type = CALIB_SOURCE_SINK_3P           },          // AI_INA_OUT1               
{           .adc_instance = INST_ADCONV1          , .adc_channel = 9           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 48           , .cal_type = CALIB_SOURCE_SINK_3P           },          // AI_INA_OUT2               
{           .adc_instance = INST_ADCONV1          , .adc_channel = 8           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 72           , .cal_type = CALIB_SOURCE_SINK_3P           },          // AI_INA_OUT3               
{           .adc_instance = INST_ADCONV1          , .adc_channel = 6           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 96           , .cal_type = CALIB_SOURCE_SINK_3P           },          // AI_INA_OUT4               
{           .adc_instance = INST_ADCONV1          , .adc_channel = 12          , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 120          , .cal_type = CALIB_SOURCE_SINK_3P           },          // AI_INA_OUT5               
{           .adc_instance = INST_ADCONV1          , .adc_channel = 13          , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 144          , .cal_type = CALIB_SOURCE_SINK_3P           },          // AI_INA_OUT6               
{           .adc_instance = INST_ADCONV1          , .adc_channel = 7           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 168          , .cal_type = CALIB_SOURCE_SINK_3P           },          // AI_INA_OUT7               
{           .adc_instance = INST_ADCONV1          , .adc_channel = 10          , .adc_vrefh = 39000          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_KL30_1                 
{           .adc_instance = INST_ADCONV1          , .adc_channel = 11          , .adc_vrefh = 39000          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_KL30_2                 
{           .adc_instance = INST_ADCONV2          , .adc_channel = 11          , .adc_vrefh = 39340          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_OUT0                   
{           .adc_instance = INST_ADCONV1          , .adc_channel = 0           , .adc_vrefh = 39340          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_OUT1                   
{           .adc_instance = INST_ADCONV2          , .adc_channel = 12          , .adc_vrefh = 39340          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_OUT2                   
{           .adc_instance = INST_ADCONV2          , .adc_channel = 13          , .adc_vrefh = 39340          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_OUT3                   
{           .adc_instance = INST_ADCONV1          , .adc_channel = 1           , .adc_vrefh = 39340          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_OUT4                   
{           .adc_instance = INST_ADCONV2          , .adc_channel = 2           , .adc_vrefh = 39340          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_OUT5                   
{           .adc_instance = INST_ADCONV2          , .adc_channel = 0           , .adc_vrefh = 39340          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_OUT6                   
{           .adc_instance = INST_ADCONV2          , .adc_channel = 1           , .adc_vrefh = 39340          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_OUT7                   
{           .adc_instance = INST_ADCONV2          , .adc_channel = 26          , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_INTERNAL_TEMP          
{           .adc_instance = INST_ADCONV2          , .adc_channel = 8           , .adc_vrefh = 32000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 0          , .cal_index = 192          , .cal_type = CALIB_SOURCE_3P                },          // AI_HSD1_CUR3              
{           .adc_instance = INST_ADCONV2          , .adc_channel = 9           , .adc_vrefh = 32000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 0          , .cal_index = 204          , .cal_type = CALIB_SOURCE_3P                },          // AI_HSD1_CUR2              
{           .adc_instance = INST_ADCONV2          , .adc_channel = 6           , .adc_vrefh = 32000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 0          , .cal_index = 216          , .cal_type = CALIB_SOURCE_3P                },          // AI_HSD1_CUR1              
{           .adc_instance = INST_ADCONV2          , .adc_channel = 7           , .adc_vrefh = 32000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 0          , .cal_index = 228          , .cal_type = CALIB_SOURCE_3P                },          // AI_HSD1_CUR0              
{           .adc_instance = INST_ADCONV2          , .adc_channel = 8           , .adc_vrefh = 32000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 1          , .cal_index = 240          , .cal_type = CALIB_SOURCE_3P                },          // AI_HSD2_CUR7              
{           .adc_instance = INST_ADCONV2          , .adc_channel = 9           , .adc_vrefh = 32000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 1          , .cal_index = 252          , .cal_type = CALIB_SOURCE_3P                },          // AI_HSD2_CUR6              
{           .adc_instance = INST_ADCONV2          , .adc_channel = 6           , .adc_vrefh = 32000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 1          , .cal_index = 264          , .cal_type = CALIB_SOURCE_3P                },          // AI_HSD2_CUR5              
{           .adc_instance = INST_ADCONV2          , .adc_channel = 7           , .adc_vrefh = 32000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 1          , .cal_index = 276          , .cal_type = CALIB_SOURCE_3P                },          // AI_HSD2_CUR4              
{           .adc_instance = INST_ADCONV2          , .adc_channel = 4           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_VARIANTE               
{           .adc_instance = INST_ADCONV2          , .adc_channel = 3           , .adc_vrefh = 14444          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_VREF                   
{           .adc_instance = INST_ADCONV2          , .adc_channel = 8           , .adc_vrefh = 32000          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_SNS1                   
{           .adc_instance = INST_ADCONV2          , .adc_channel = 9           , .adc_vrefh = 32000          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_SNS2                   
{           .adc_instance = INST_ADCONV2          , .adc_channel = 6           , .adc_vrefh = 32000          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_SNS3                   
{           .adc_instance = INST_ADCONV2          , .adc_channel = 7           , .adc_vrefh = 32000          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                     },          // AI_SNS4                   
 
};

/* PWM config table */
const struct_FTM_CONFIG struct_ftm_config_tbl[FREQ_MAX + 1] = {

            // PWM instance of the pin           , // PWM channel             , // current sense ADC channel                                                 
{           .pwm_instance = MODULE_2             , .pwm_channel = 5           , .adc_pin_name = AI_INA_OUT0            },          // PWM_HSD1_OUT0          
{           .pwm_instance = MODULE_0             , .pwm_channel = 4           , .adc_pin_name = AI_INA_OUT1            },          // PWM_HSD1_OUT1          
{           .pwm_instance = MODULE_0             , .pwm_channel = 6           , .adc_pin_name = AI_INA_OUT2            },          // PWM_HSD1_OUT2          
{           .pwm_instance = MODULE_0             , .pwm_channel = 5           , .adc_pin_name = AI_INA_OUT3            },          // PWM_HSD1_OUT3          
{           .pwm_instance = MODULE_2             , .pwm_channel = 3           , .adc_pin_name = AI_INA_OUT4            },          // PWM_HSD2_OUT4          
{           .pwm_instance = MODULE_2             , .pwm_channel = 2           , .adc_pin_name = AI_INA_OUT5            },          // PWM_HSD2_OUT5          
{           .pwm_instance = MODULE_1             , .pwm_channel = 5           , .adc_pin_name = AI_INA_OUT6            },          // PWM_HSD2_OUT6          
{           .pwm_instance = MODULE_0             , .pwm_channel = 1           , .adc_pin_name = AI_INA_OUT7            },          // PWM_HSD2_OUT7          
{           .pwm_instance = MODULE_NONE          , .pwm_channel = -1          , .adc_pin_name = ADC_MAX                },          // PWM_MAX                
{           .pwm_instance = MODULE_3             , .pwm_channel = 5           , .adc_pin_name = ADC_MAX                },          // FREQ_A_IN1             
{           .pwm_instance = MODULE_3             , .pwm_channel = 6           , .adc_pin_name = ADC_MAX                },          // FREQ_A_IN2             
{           .pwm_instance = MODULE_3             , .pwm_channel = 7           , .adc_pin_name = ADC_MAX                },          // FREQ_A_IN3             
{           .pwm_instance = MODULE_3             , .pwm_channel = 1           , .adc_pin_name = ADC_MAX                },          // FREQ_A_IN4             
{           .pwm_instance = MODULE_3             , .pwm_channel = 2           , .adc_pin_name = ADC_MAX                },          // FREQ_A_IN5             
{           .pwm_instance = MODULE_3             , .pwm_channel = 4           , .adc_pin_name = ADC_MAX                },          // FREQ_A_IN0             
{           .pwm_instance = MODULE_NONE          , .pwm_channel = -1          , .adc_pin_name = ADC_MAX                },          // FREQ_MAX               
};
